<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="application" nsURI="http://www.toedter.com/e4/UIModel/application"
    nsPrefix="application">
  <eSubpackages name="ui" nsURI="http://www.toedter.com/e4/UIModel/application/ui"
      nsPrefix="ui">
    <eSubpackages name="basic" nsURI="http://www.toedter.com/e4/UIModel/application/ui/basic"
        nsPrefix="basic">
      <eClassifiers xsi:type="ecore:EClass" name="TutorialPartStack" eSuperTypes="platform:/plugin/org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//ui/basic/PartStack">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="myRenderer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
